module.exports = [
  { id: 1, user_id: 1, lat: 49.2827, lng: -123.1207, comment: "Amidst the cityscape, I marveled at the modern architecture and bustling streets that define downtown Vancouver.", likes: 15 },
  { id: 2, user_id: 2, lat: 49.2816, lng: -123.1316, comment: "Strolling through Kitsilano, I was captivated by the scenic views of the ocean and the laid-back charm of the neighborhood.", likes: 20 },
  { id: 3, user_id: 3, lat: 49.2698, lng: -123.1551, comment: "At this viewpoint, the majestic mountains in the distance create a breathtaking backdrop to the urban cityscape.", likes: 10 },
  { id: 4, user_id: 1, lat: 49.2821, lng: -123.1056, comment: "Exploring Gastown's cobblestone streets, I uncovered hidden gems and felt the history embedded in the brick facades.", likes: 8 },
  { id: 5, user_id: 2, lat: 49.2685, lng: -123.1104, comment: "From this vantage point, the towering skyscrapers against the sky painted a picture of ambition and dreams in the heart of the city.", likes: 25 },
  { id: 6, user_id: 3, lat: 49.2712, lng: -123.1542, comment: "Kitsilano's shoreline offered a panorama of sandy beaches, ocean waves, and distant mountains, creating a serene and picturesque setting.", likes: 18 },
  { id: 7, user_id: 1, lat: 49.2779, lng: -123.1239, comment: "Navigating the diverse neighborhoods, I discovered vibrant murals and street art that added color to the urban labyrinth.", likes: 12 },
  { id: 8, user_id: 2, lat: 49.2773, lng: -123.1259, comment: "At the crossroads of life, the city's intersections became a metaphor for choices and opportunities unfolding at every turn.", likes: 30 },
  { id: 9, user_id: 3, lat: 49.2638, lng: -123.1571, comment: "In the shadows of the North Shore mountains, I found strength and resilience mirrored in the challenges of the landscape.", likes: 22 },
  { id: 10, user_id: 1, lat: 49.2807, lng: -123.1153, comment: "Embracing the harmonious blend of city life and coastal tranquility, I felt the symphony of urban hustle and natural serenity.", likes: 14 },
  { id: 11, user_id: 2, lat: 49.2686, lng: -123.1070, comment: "Immersed in cultural richness, I appreciated the diverse architecture and traditions that collectively shaped the city's identity.", likes: 28 },
  { id: 12, user_id: 3, lat: 49.2802, lng: -123.1105, comment: "At this longitude of life, memories converged like rivers, each flowing with experiences that shaped the tapestry of my journey.", likes: 16 },
  { id: 13, user_id: 1, lat: 49.2770, lng: -123.1252, comment: "Amongst the whispers of trees and city symphonies, I found solace in the harmonious coexistence of nature and urban life.", likes: 19 },
  { id: 14, user_id: 2, lat: 49.2761, lng: -123.1189, comment: "This coordinate on the map marked a node in the interconnected web of breathtaking beauty, a testament to the city's diverse landscapes.", likes: 11 },
  { id: 15, user_id: 3, lat: 49.2811, lng: -123.1213, comment: "Tracing the lines of longitude, I uncovered a city narrative that weaves stories of resilience and determination against the urban backdrop.", likes: 24 },
  { id: 16, user_id: 1, lat: 49.2699, lng: -123.1140, comment: "Bridging the gaps between neighborhoods, cultures, and dreams, I found unity as the truest form of beauty in the cityscape.", likes: 17 },
  { id: 17, user_id: 2, lat: 49.2750, lng: -123.1180, comment: "At the meeting point of cityscape and seascape, I had an epiphany that beauty resides in the harmonious dance of dreams and tides.", likes: 21 },
  { id: 18, user_id: 3, lat: 49.2785, lng: -123.1327, comment: "A marker on the globe, this point embraced the collective consciousness, where the city's beauty echoed through the hearts of its people.", likes: 23 },
  { id: 19, user_id: 1, lat: 49.2735, lng: -123.1319, comment: "An invisible thread connected the city's past, present, and future, unveiling the timeless beauty within every corner and alley.", likes: 27 },
  { id: 20, user_id: 2, lat: 49.2800, lng: -123.1125, comment: "In the pulse of the city, feeling the heartbeat of a vibrant community, I realized that beauty is alive in every moment and every lively street.", likes: 26 },
];
