module.exports = [
  { id: 1, user_id: 1, promo: "Check out John Doe's latest art exhibition at the downtown gallery!" },
  { id: 2, user_id: 2, promo: "Jane Smith's handmade jewelry collection is now available for purchase. Don't miss it!" },
  { id: 3, user_id: 3, promo: "Bob Johnson's photography workshop: Learn the art of capturing moments. Limited seats available!" },
  { id: 4, user_id: 4, promo: "Discover Alice Williams' unique fashion designs. Exclusive discounts for early customers!" },
  { id: 5, user_id: 5, promo: "Charlie Brown's music album release party this weekend. Join us for a night of great music!" },
  { id: 6, user_id: 6, promo: "Eva Davis presents her new book: 'The Journey Within.' Available in stores now!" },
  { id: 7, user_id: 7, promo: "Frank Miller's art prints: Bring the beauty of nature into your home. Limited edition prints available." },
  { id: 8, user_id: 8, promo: "Grace Taylor's online cooking classes: Master the art of gourmet cooking from the comfort of your home." },
  { id: 9, user_id: 9, promo: "Henry Wilson's podcast: Unleash your potential. Tune in for inspiring stories and practical advice." },
  { id: 10, user_id: 10, promo: "Ivy Anderson's dance workshop: Join the movement! Learn the art of expression through dance." },
  { id: 11, user_id: 1, promo: "John Doe's exclusive painting exhibition is coming to your city. Reserve your tickets now!" },
  { id: 12, user_id: 2, promo: "Jane Smith's handcrafted silver jewelry: Perfect gifts for your loved ones. Order today!" },
  { id: 13, user_id: 3, promo: "Bob Johnson's photography masterclass: Learn the secrets behind stunning visual storytelling." },
  { id: 14, user_id: 4, promo: "Alice Williams' fashion show: Be the first to witness the latest trends on the runway." },
  { id: 15, user_id: 5, promo: "Charlie Brown's new album is out! Stream it now on your favorite music platform." },
  { id: 16, user_id: 6, promo: "Eva Davis' book signing event: Meet the author and get a signed copy of 'The Journey Within.'" },
  { id: 17, user_id: 7, promo: "Frank Miller's art exhibition: Explore the fusion of art and technology in his latest creations." },
  { id: 18, user_id: 8, promo: "Grace Taylor's culinary tour: Join her on a gastronomic adventure around the world." },
  { id: 19, user_id: 9, promo: "Henry Wilson's motivational podcast: Start your day with positivity and inspiration." },
  { id: 20, user_id: 10, promo: "Ivy Anderson's dance performance: Witness the magic of movement and expression live on stage." },
  { id: 21, user_id: 1, promo: "John Doe's art workshop: Unleash your creativity with hands-on painting sessions. Limited spots available!" },
  { id: 22, user_id: 2, promo: "Jane Smith's jewelry pop-up shop: Visit our booth at the local market and explore unique designs." },
  { id: 23, user_id: 3, promo: "Bob Johnson's photography book launch: Dive into the world of captivating visuals and behind-the-scenes stories." },
  { id: 24, user_id: 4, promo: "Alice Williams' fashion blog: Stay updated on the latest trends and style tips from a seasoned fashionista." },
  { id: 25, user_id: 5, promo: "Charlie Brown's music collaboration: Join the fan club for exclusive previews of upcoming collaborations." },
  { id: 26, user_id: 6, promo: "Eva Davis' writing retreat: Join aspiring writers for a weekend of creativity and inspiration." },
  { id: 27, user_id: 7, promo: "Frank Miller's digital art exhibition: Experience the future of art in a virtual gallery space." },
  { id: 28, user_id: 8, promo: "Grace Taylor's cooking blog: Explore mouth-watering recipes and cooking hacks for every home chef." },
  { id: 29, user_id: 9, promo: "Henry Wilson's life coaching sessions: Transform your life with personalized coaching and guidance." },
  { id: 30, user_id: 10, promo: "Ivy Anderson's dance fitness classes: Stay fit while expressing yourself through dance. Join the movement!" },
  { id: 31, user_id: 1, promo: "John Doe's art podcast: Dive into the world of artistic insights and interviews with renowned creatives." },
  { id: 32, user_id: 2, promo: "Jane Smith's jewelry-making workshops: Learn the art of crafting beautiful pieces from a master jeweler." },
  { id: 33, user_id: 3, promo: "Bob Johnson's photography exhibition tour: Catch breathtaking visuals at a gallery near you." },
  { id: 34, user_id: 4, promo: "Alice Williams' fashion design masterclass: Turn your passion for fashion into a career." },
  { id: 35, user_id: 5, promo: "Charlie Brown's live music streaming: Enjoy weekly live sessions from the comfort of your home." },
  { id: 36, user_id: 6, promo: "Eva Davis' book club: Join a community of readers exploring thought-provoking literature." },
  { id: 37, user_id: 7, promo: "Frank Miller's art gallery opening: Witness a visual feast featuring his latest masterpieces." },
  { id: 38, user_id: 8, promo: "Grace Taylor's cooking classes for beginners: Start your culinary journey with expert guidance." },
  { id: 39, user_id: 9, promo: "Henry Wilson's self-development webinar: Unlock your full potential with practical strategies." },
  { id: 40, user_id: 10, promo: "Ivy Anderson's dance therapy sessions: Heal and rejuvenate through the power of dance movement." }
];