module.exports = [
  { id: 1, user_id: 1, promo: "This was posts by an anonymous explorer!", link: "" },
  { id: 2, user_id: 2, promo: "Olivia Baker's fitness journey: Join a community of fitness enthusiasts and share your progress.", link: "https://www.myfitnesspal.com" },
  { id: 3, user_id: 3, promo: "Nathan Hill's backyard gardening tips: Grow your own fresh produce at home.", link: "https://www.almanac.com" },
  { id: 4, user_id: 4, promo: "Emily Fisher' beauty and skincare tutorials: Discover effective beauty routines.", link: "https://www.byrdie.com" },
  { id: 5, user_id: 5, promo: "Daniel Clark's pet care vlogs: Ensure the well-being of your furry friends.", link: "https://www.thesprucepets.com" },
  { id: 6, user_id: 6, promo: "Sophoa Murray' home decor inspiration: Transform your living spaces with creative ideas.", link: "https://www.houzz.com" },
  { id: 7, user_id: 7, promo: "Caleb Mitchell's personal finance blog: Gain insights for a secure financial future.", link: "https://www.nerdwallet.com" },
  { id: 8, user_id: 8, promo: "Isabella Porter's plant-based recipes: Enjoy delicious and nutritious meals.", link: "https://www.forksoverknives.com" },
  { id: 9, user_id: 9, promo: "Owen Wright's tech gadget reviews: Stay updated on the latest tech innovations.", link: "https://www.theverge.com" },
  { id: 10, user_id: 10, promo: "Ava Rich's art therapy sessions: Explore creativity for mental well-being.", link: "https://www.arttherapy.org" },
  { id: 11, user_id: 3, promo: "Adam Johnson's outdoor adventure blog: Embark on thrilling journeys and discover hidden gems.", link: "https://www.atlasobscura.com" },
  { id: 12, user_id: 2, promo: "Olivia Baker's book club: Join a community of book lovers and explore diverse literary works.", link: "https://www.goodreads.com" },
  { id: 13, user_id: 3, promo: "Nathan Hill's DIY woodworking projects: Create functional and beautiful pieces for your home.", link: "https://www.popularwoodworking.com" },
  { id: 14, user_id: 4, promo: "Emily Fisher' fashion styling tips: Elevate your style with expert fashion advice.", link: "https://www.whowhatwear.com" },
  { id: 15, user_id: 5, promo: "Daniel Clark's music playlist recommendations: Discover new tunes for every mood.", link: "https://www.spotify.com" },
  { id: 16, user_id: 6, promo: "Sophoa Murray' travel planning guides: Plan your next adventure with insider tips.", link: "https://www.lonelyplanet.com" },
  { id: 17, user_id: 7, promo: "Caleb Mitchell's mindfulness meditation sessions: Find peace in your daily life.", link: "https://www.headspace.com" },
  { id: 18, user_id: 8, promo: "Isabella Porter's DIY natural beauty products: Create skincare essentials at home.", link: "https://www.wellandgood.com" },
  { id: 19, user_id: 9, promo: "Owen Wright's coding tutorials: Learn programming with clear and concise lessons.", link: "https://www.freecodecamp.org" },
  { id: 20, user_id: 10, promo: "Ava Rich's dance fitness classes: Stay fit while expressing yourself through dance.", link: "https://www.dancebody.com" },
  { id: 21, user_id: 3, promo: "Adam Johnson's tech news blog: Stay informed about the latest in the tech world.", link: "https://www.techcrunch.com" },
  { id: 22, user_id: 2, promo: "Olivia Baker's home workout routines: Achieve your fitness goals with quick and effective exercises.", link: "https://www.fitnessblender.com" },
  { id: 23, user_id: 3, promo: "Nathan Hill's classic car restoration guides: Restore vintage cars to their former glory.", link: "https://www.hemmings.com" },
  { id: 24, user_id: 4, promo: "Emily Fisher' travel essentials store: Explore must-have items for your journeys.", link: "https://www.rei.com" },
  { id: 25, user_id: 5, promo: "Daniel Clark's indie music recommendations: Discover hidden gems in the music scene.", link: "https://www.pitchfork.com" },
  { id: 26, user_id: 6, promo: "Sophoa Murray' eco-friendly living blog: Embrace sustainable practices for a greener lifestyle.", link: "https://www.treehugger.com" },
  { id: 27, user_id: 7, promo: "Caleb Mitchell's investment advice platform: Navigate the world of investments with confidence.", link: "https://www.investopedia.com" },
  { id: 28, user_id: 8, promo: "Isabella Porter's yoga and mindfulness retreats: Find balance and serenity in beautiful locations.", link: "https://www.yogajournal.com" },
  { id: 29, user_id: 9, promo: "Owen Wright's AI and robotics showcase: Explore the cutting-edge world of artificial intelligence.", link: "https://www.roboticsbusinessreview.com" },
  { id: 30, user_id: 10, promo: "Ava Rich's creative writing workshops: Unleash your creativity and write compelling stories.", link: "https://www.writersworkshop.com" },
  { id: 31, user_id: 3, promo: "Adam Johnson's astronomy enthusiasts forum: Connect with fellow stargazers and share your observations.", link: "https://www.cloudynights.com" },
  { id: 32, user_id: 2, promo: "Olivia Baker's healthy cooking classes: Learn to prepare delicious and nutritious meals.", link: "https://www.cookinglight.com" },
  { id: 33, user_id: 3, promo: "Nathan Hill's vintage vinyl record store: Build your collection with timeless classics.", link: "https://www.discogs.com" },
  { id: 34, user_id: 4, promo: "Emily Fisher' fashion design portfolio: Explore a showcase of unique and stylish designs.", link: "https://www.behance.net" },
  { id: 35, user_id: 5, promo: "Daniel Clark's live music streaming: Enjoy weekly live sessions from the comfort of your home.", link: "https://www.livefromhome.com" },
  { id: 36, user_id: 6, promo: "Sophoa Murray' DIY natural beauty products: Create skincare essentials using simple ingredients.", link: "https://www.wellandgood.com" },
  { id: 37, user_id: 7, promo: "Caleb Mitchell's personal development podcast: Elevate your life with insightful discussions.", link: "https://www.ted.com" },
  { id: 38, user_id: 8, promo: "Isabella Porter's sustainable fashion marketplace: Shop ethically curated clothing.", link: "https://www.therealreal.com" },
  { id: 39, user_id: 9, promo: "Owen Wright's coding bootcamp: Kickstart your coding journey with intensive courses.", link: "https://www.udacity.com" },
  { id: 40, user_id: 10, promo: "Ava Rich's dance fitness app: Stay fit and have fun with dance-inspired workouts.", link: "https://www.dancebody.com" },
  { id: 41, user_id: 3, promo: "Adam Johnson's coding tutorials: Learn programming with practical examples.", link: "https://www.freecodecamp.org" },
  { id: 42, user_id: 2, promo: "Olivia Baker's sustainable living blog: Embrace eco-friendly practices for a greener lifestyle.", link: "https://www.earth911.com" },
  { id: 43, user_id: 3, promo: "Nathan Hill's woodworking masterclass: Craft beautiful pieces with expert guidance.", link: "https://www.finewoodworking.com" },
  { id: 44, user_id: 4, promo: "Emily Fisher' art therapy sessions: Explore creativity as a tool for well-being.", link: "https://www.arttherapy.org" },
  { id: 45, user_id: 5, promo: "Daniel Clark's adventure travel vlogs: Embark on thrilling journeys around the world.", link: "https://www.nationalgeographic.com/travel" },
  { id: 46, user_id: 6, promo: "Sophoa Murray' virtual reality gaming experience: Immerse yourself in the future of gaming.", link: "https://www.oculus.com" },
  { id: 47, user_id: 7, promo: "Caleb Mitchell's cocktail recipes: Shake up your mixology skills with creative drinks.", link: "https://www.diffordsguide.com" },
  { id: 48, user_id: 8, promo: "Isabella Porter's mindfulness app: Find peace and relaxation in your daily life.", link: "https://www.calm.com" },
  { id: 49, user_id: 9, promo: "Owen Wright's outdoor photography workshops: Capture stunning visuals in nature.", link: "https://www.outdoorphotoworkshops.com" },
  { id: 50, user_id: 10, promo: "Ava Rich's language exchange platform: Connect with language learners worldwide.", link: "https://www.tandem.net" },
  { id: 51, user_id: 3, promo: "Adam Johnson's DIY home improvement tutorials: Upgrade your space with expert tips.", link: "https://www.thisoldhouse.com" },
  { id: 52, user_id: 2, promo: "Olivia Baker's pet care vlogs: Ensure the happiness and health of your furry companions.", link: "https://www.thesprucepets.com" },
  { id: 53, user_id: 3, promo: "Nathan Hill's vintage video game reviews: Relive the nostalgia of classic games.", link: "https://www.retrogamer.net" },
  { id: 54, user_id: 4, promo: "Emily Fisher' fashion design masterclass: Turn your passion for fashion into a career.", link: "https://www.skillshare.com" },
  { id: 55, user_id: 5, promo: "Daniel Clark's live music streaming: Enjoy weekly live sessions from the comfort of your home.", link: "https://www.livefromhome.com" },
  { id: 56, user_id: 6, promo: "Sophoa Murray' DIY natural beauty products: Create skincare essentials using simple ingredients.", link: "https://www.wellandgood.com" },
  { id: 57, user_id: 7, promo: "Caleb Mitchell's personal development podcast: Elevate your life with insightful discussions.", link: "https://www.ted.com" },
  { id: 58, user_id: 8, promo: "Isabella Porter's sustainable fashion marketplace: Shop ethically curated clothing.", link: "https://www.therealreal.com" },
  { id: 59, user_id: 9, promo: "Owen Wright's coding bootcamp: Kickstart your coding journey with intensive courses.", link: "https://www.udacity.com" },
  { id: 60, user_id: 10, promo: "Ava Rich's dance fitness app: Stay fit and have fun with dance-inspired workouts.", link: "https://www.dancebody.com" },
  { id: 61, user_id: 3, promo: "Adam Johnson's tech news blog: Stay informed about the latest in the tech world.", link: "https://www.techcrunch.com" },
  { id: 62, user_id: 2, promo: "Olivia Baker's home workout routines: Achieve your fitness goals with quick and effective exercises.", link: "https://www.fitnessblender.com" },
  { id: 63, user_id: 3, promo: "Nathan Hill's classic car restoration guides: Restore vintage cars to their former glory.", link: "https://www.hemmings.com" },
  { id: 64, user_id: 4, promo: "Emily Fisher' travel essentials store: Explore must-have items for your journeys.", link: "https://www.rei.com" },
  { id: 65, user_id: 5, promo: "Daniel Clark's indie music recommendations: Discover hidden gems in the music scene.", link: "https://www.pitchfork.com" },
  { id: 66, user_id: 6, promo: "Sophoa Murray' eco-friendly living blog: Embrace sustainable practices for a greener lifestyle.", link: "https://www.treehugger.com" },
  { id: 67, user_id: 7, promo: "Caleb Mitchell's investment advice platform: Navigate the world of investments with confidence.", link: "https://www.investopedia.com" },
  { id: 68, user_id: 8, promo: "Isabella Porter's yoga and mindfulness retreats: Find balance and serenity in beautiful locations.", link: "https://www.yogajournal.com" },
  { id: 69, user_id: 9, promo: "Owen Wright's AI and robotics showcase: Explore the cutting-edge world of artificial intelligence.", link: "https://www.roboticsbusinessreview.com" },
  { id: 70, user_id: 10, promo: "Ava Rich's dance fitness app: Stay fit and have fun with dance-inspired workouts.", link: "https://www.dancebody.com" },
  { id: 71, user_id: 3, promo: "Adam Johnson's sustainable living hacks: Adopt eco-friendly practices in your daily life.", link: "https://www.ecowatch.com" },
  { id: 72, user_id: 2, promo: "Olivia Baker's photography tutorials: Capture stunning moments with expert guidance.", link: "https://www.digital-photography-school.com" },
  { id: 73, user_id: 3, promo: "Nathan Hill's DIY car maintenance: Keep your vehicle running smoothly with simple tips.", link: "https://www.hagerty.com" },
  { id: 74, user_id: 4, promo: "Emily Fisher' minimalist lifestyle blog: Simplify your life and find joy in the essentials.", link: "https://www.becomingminimalist.com" },
  { id: 75, user_id: 5, promo: "Daniel Clark's gaming livestreams: Join the gaming community for exciting gameplay.", link: "https://www.twitch.tv" },
  { id: 76, user_id: 6, promo: "Sophoa Murray' DIY home decor ideas: Transform your space with budget-friendly projects.", link: "https://www.apartmenttherapy.com" },
  { id: 77, user_id: 7, promo: "Caleb Mitchell's career advice platform: Navigate your professional journey with expert insights.", link: "https://www.linkedin.com" },
  { id: 78, user_id: 8, promo: "Isabella Porter's organic gardening tips: Cultivate a flourishing garden using natural methods.", link: "https://www.motherearthnews.com" },
  { id: 79, user_id: 9, promo: "Owen Wright's futuristic tech reviews: Explore the latest advancements in technology.", link: "https://www.wired.com" },
  { id: 80, user_id: 10, promo: "Ava Rich's DIY craft projects: Create beautiful and personalized items for your home.", link: "https://www.marthastewart.com" },
  { id: 81, user_id: 3, promo: "Adam Johnson's mindfulness and meditation app: Cultivate inner peace in your busy life.", link: "https://www.headspace.com" },
  { id: 82, user_id: 2, promo: "Olivia Baker's language learning platform: Master a new language with interactive lessons.", link: "https://www.duolingo.com" },
  { id: 83, user_id: 3, promo: "Nathan Hill's classic movie reviews: Rediscover timeless films and hidden gems.", link: "https://www.rottentomatoes.com" },
  { id: 84, user_id: 4, promo: "Emily Fisher' fashion illustration tutorials: Learn the art of sketching stylish outfits.", link: "https://www.skillshare.com" },
  { id: 85, user_id: 5, promo: "Daniel Clark's virtual reality experiences: Dive into immersive worlds with VR technology.", link: "https://www.oculus.com" },
  { id: 86, user_id: 6, promo: "Sophoa Murray' plant-based cooking classes: Explore delicious and healthy vegan recipes.", link: "https://www.forksoverknives.com" },
  { id: 87, user_id: 7, promo: "Caleb Mitchell's productivity hacks: Optimize your work and personal life for success.", link: "https://www.lifehacker.com" },
  { id: 88, user_id: 8, promo: "Isabella Porter's DIY natural beauty products: Create skincare essentials at home.", link: "https://www.wellandgood.com" },
  { id: 89, user_id: 9, promo: "Owen Wright's coding challenges: Sharpen your programming skills with interactive challenges.", link: "https://www.codewars.com" },
  { id: 90, user_id: 10, promo: "Ava Rich's dance tutorials: Learn dance styles from around the world in easy steps.", link: "https://www.steezy.co" },
  { id: 91, user_id: 3, promo: "Adam Johnson's DIY tech projects: Build cool gadgets with step-by-step guides.", link: "https://www.instructables.com" },
  { id: 92, user_id: 2, promo: "Olivia Baker's wellness retreats: Rejuvenate your mind and body in serene locations.", link: "https://www.wellnessliving.com" },
  { id: 93, user_id: 3, promo: "Nathan Hill's classic literature book club: Explore timeless literary works with fellow enthusiasts.", link: "https://www.goodreads.com" },
  { id: 94, user_id: 4, promo: "Emily Fisher' sustainable fashion boutique: Shop for eco-friendly and stylish clothing.", link: "https://www.reformation.com" },
  { id: 95, user_id: 5, promo: "Daniel Clark's vinyl record recommendations: Discover the richness of analog music.", link: "https://www.vinylmeplease.com" },
  { id: 96, user_id: 6, promo: "Sophoa Murray' DIY home spa treatments: Pamper yourself with easy-to-make spa essentials.", link: "https://www.self.com" },
  { id: 97, user_id: 7, promo: "Caleb Mitchell's stock trading insights: Learn strategies for successful stock market investing.", link: "https://www.stocktwits.com" },
  { id: 98, user_id: 8, promo: "Isabella Porter's plant-based lifestyle vlogs: Embrace a cruelty-free and sustainable way of living.", link: "https://www.livekindly.co" },
  { id: 99, user_id: 9, promo: "Owen Wright's cybersecurity tutorials: Strengthen your online security with expert tips.", link: "https://www.cybrary.it" },
  { id: 100, user_id: 10, promo: "Ava Rich's online painting classes: Unleash your creativity with virtual painting sessions.", link: "https://www.skillshare.com" },
  { id: 101, user_id: 3, promo: "Adam Johnson's nature photography workshops: Capture the beauty of the great outdoors.", link: "https://www.outdoorphotoworkshops.com" },
  { id: 102, user_id: 2, promo: "Olivia Baker's travel blogging community: Share your travel experiences and tips with a global audience.", link: "https://www.travelblog.org" },
  { id: 103, user_id: 3, promo: "Nathan Hill's vintage comic book store: Explore rare and collectible comic treasures.", link: "https://www.milehighcomics.com" },
  { id: 104, user_id: 4, promo: "Emily Fisher' sustainable beauty products store: Embrace eco-friendly skincare.", link: "https://www.thedetoxmarket.com" },
  { id: 105, user_id: 5, promo: "Daniel Clark's indie game development tutorials: Create your own video games.", link: "https://www.gamasutra.com" },
  { id: 106, user_id: 6, promo: "Sophoa Murray' DIY natural cleaning products: Keep your home sparkling with homemade solutions.", link: "https://www.cleanmyspace.com" },
  { id: 107, user_id: 7, promo: "Caleb Mitchell's personal finance podcast: Gain financial wisdom for a secure future.", link: "https://www.listenmoneymatters.com" },
  { id: 108, user_id: 8, promo: "Isabella Porter's sustainable living store: Shop consciously curated eco-friendly products.", link: "https://www.packagefreeshop.com" },
  { id: 109, user_id: 9, promo: "Owen Wright's coding challenges: Sharpen your programming skills with interactive tasks.", link: "https://www.codewars.com" },
  { id: 110, user_id: 10, promo: "Ava Rich's dance tutorials: Learn dance styles from around the world in easy steps.", link: "https://www.steezy.co" },

]
