module.exports = [
  { id: 1, username: "Anonymous", email: "samuel.taylor@example.com", city: "Vancouver", password: "samuelPassword", avatar: "http://34.221.97.0/avatars/anonymous.png", description: "Anonymous mind are some of the best." },
  { id: 2, username: "Olivia Baker", email: "olivia.baker@example.com", city: "Vancouver", password: "oliviaPassword", avatar: "http://34.221.97.0/avatars/olivia.jpg", description: "I find solace and inspiration in the rhythm of words, expressing my thoughts through poetry." },
  { id: 3, username: "Nathan Hill", email: "nathan.hill@example.com", city: "Vancouver", password: "nathanPassword", avatar: "http://34.221.97.0/avatars/caleb.jpg", description: "The streets are my stage, and I captivate audiences with my mesmerizing performances." },
  { id: 4, username: "Emily Fisher", email: "emily.fisher@example.com", city: "Vancouver", password: "emilyPassword", avatar: "http://34.221.97.0/avatars/emily.jpg", description: "I'm passionate about causes that matter, advocating for positive change in our community." },
  { id: 5, username: "Daniel Clark", email: "daniel.clark@example.com", city: "Vancouver", password: "danielPassword", avatar: "http://34.221.97.0/avatars/daniel.jpg", description: "Navigating the political landscape, I strive to make a difference and represent the people." },
  { id: 6, username: "Sophia Murray", email: "sophia.murray@example.com", city: "Vancouver", password: "sophiaPassword", avatar: "http://34.221.97.0/avatars/olivia.jpg", description: "Small buisness owner. I love watching my dreams grow, and I chase them. Every. Single. Day." },
  { id: 7, username: "Caleb Mitchell", email: "caleb.mitchell@example.com", city: "Vancouver", password: "calebPassword", avatar: "http://34.221.97.0/avatars/caleb.jpg", description: "Words have a melody of their own, and I compose poetry to share the beauty of language." },
  { id: 8, username: "Isabella Porter", email: "isabella.porter@example.com", city: "Vancouver", password: "isabellaPassword", avatar: "http://34.221.97.0/avatars/isabella.jpg", description: "The streets are my canvas, and I express my art to brighten people's days." },
  { id: 9, username: "Owen Wright", email: "owen.wright@example.com", city: "Vancouver", password: "owenPassword", avatar: "http://34.221.97.0/avatars/owen.jpg", description: "Passionate about causes that matter, I actively work towards creating a positive impact." },
  { id: 10, username: "Ava Rich", email: "ava.richards@example.com", city: "Vancouver", password: "avaPassword", avatar: "http://34.221.97.0/avatars/ava.jpg", description: "In the realm of politics, I aim to be a voice for the people, advocating for their needs." },
  { id: 11, username: "Test Profile", email: "1@1.com", city: "Vancouver", password: "11111", avatar: "http://34.221.97.0/avatars/anonymous.png", description: "This is a user profile for test purposes." },
  { id: 12, username: "Kevin Byrne", email: "kevinspbyrne@gmail.com", city: "Vancouver", password: "11111", avatar: "http://34.221.97.0/avatars/anonymous.png", description: "This is a user profile for test purposes." }
]